name: Code style and static analysis

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Update configs
        run: php tools/prepare-configs.php

      - name: Run script
        run: vendor/bin/phpcs

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.3'
        coverage: [ 'none' ]
        doctrine-orm-versions:
          - '^2.17'
          - '^3.0'

    name: Static analyse with PHP ${{ matrix.php }} Doctrine ${{ matrix.doctrine-orm-versions }} ${{ matrix.description }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Update package versions
        run: |
          composer require doctrine/orm:${{ matrix.doctrine-orm-versions }} --no-update --no-scripts -W

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run script
        run: |
          php tools/prepare-configs.php;
          vendor/bin/phpstan analyse

  composer-validate:
    name: Composer validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run script
        run: composer composer-validate
